learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls')),
    
]

learning_logs/urls.py
'''Defining urls patterns for learning_logs'''

from django.urls import path
from . import views



app_name='learning_logs'
urlpatterns=[
    # Home page
    path('',views.index,name='index'),
    #page that shows all topics
   
    #Detail page for a single topic
    
]

learning_logs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    """A topic the user is learning about."""
    text=models.CharField(max_length=200)
    data_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text
    
class Entry(models.Model):
    """Something specific learned about a topic"""
    topic=models.ForeignKey(Topic, on_delete=models.CASCADE)
    text=models.TextField()
    data_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='entries'

        def __str__(self):
            """Return a string representation of the model."""
            return f"{self.text[:50]}..."

learning_logs/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    """The home page for Learning Logs."""
    return render(request, 'learning_logs/index.html')

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}" >Learning Log</a>
   
</p>

{% block content %} {% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p> learning Log</p>

    <p>Learning log help you keep track of your learning, for any topic you're learnig about</p>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% block content %}
<p>Topic:{{ topic }}</p>
<p>Entries:</p>
<ul>
{% for entry in entries %}
    <li>
        <p>{{entry.date_added|date:'M d, Y H:i'}}</p>
        <p>{{entry.text|linebreaks}}</p>
    </li>
{% empty %}
    <li>There are no entries for this topic yet.</li>
{% endfor %}
</ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% block content %}
<p>Topics</p>
<ul>
    {% for topic in topics %}
        <li>{{ topic }}</li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
{% endblock content %}